### ISSUE TITLE
False positive in "potentially uninitialized variable"

### ISSUE THREAD

**Issue by amueller** [lgtmhq/lgtm-queries#11] opened 2017-07-05 15:27 UTC
Hey.
I just took a brief look at lgtm and it looks awesome, thanks folks :)
If it's helpful, I'm happy to report false positives.
Here is one example:
https://lgtm.com/projects/g/scikit-learn/scikit-learn/snapshot/1a981e87ba6f8d66ecfd6940184836446ded3f4c/files/sklearn/cross_validation.py#V937

There is an ``if test_size is None`` and later an ``if test_size is not None`` and both define  ``n_test``.
I imagine that if the code was written using ``if .. else ..`` it would be detected correctly, but splitting it up in two ifs makes it harder to detect?
(arguably it's also not the best coding style ;)

**Comment by markshannon** [comment] 2017-07-05 15:54
Thanks for the report. 
This does look like a false positive, but it is more complicated than you suggest.
The definitions of `n_test` are on lines 922 and 924. If `np.asarray(test_size).dtype.kind` were neither "f" nor "i", then `n_test` would be undefined.
However, the `if` statement on line 889 ensures that `np.asarray(test_size).dtype.kind` must be either "f" or "i".
Due to the complexity of the tests involved, I don't see an obvious fix for this I'm afraid.

**Comment by amueller** [comment] 2017-07-05 15:56
You're right, I missed the dtype checking. It's a bit convoluted, and maybe this is a false positive but points to code that is unnecessarily complex.

**Comment by sjvs** [comment] 2017-08-16 11:37
@amueller: we'll soon introduce functionality to suppress alerts on lgtm.com using code comments. Keep an eye out for it! I'll close this for now. If you notice any other unexpected behaviour: please let us know.

**Closed by sjvs** 2017-08-16 11:37 UTC
